backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  # This line should *not* be indented
# publish_mode: editorial_workflow
# These lines should *not* be indented
media_folder: static/assets
public_folder: /assets

collections:
  - name: vacancies
    label: Vacancies
    folder: content/vacancies
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: promotions
    label: Promotions
    folder: content/promotions
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - { label: title-one, name: title-one, widget: string }
          - { label: subtitle-one, name: subtitle-one, widget: string }
          - { label: title-two, name: subtitle-two, widget: string }
          - { label: subtitle-two, name: subtitle-two, widget: string }
          - { label: title-three, name: subtitle-three, widget: string }
          - { label: subtitle-three, name: subtitle-three, widget: string }
