backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  # This line should *not* be indented
# publish_mode: editorial_workflow
# These lines should *not* be indented
media_folder: static/assets/images/uploads
public_folder: /assets/images/uploads

collections:
  - name: vacancies
    label: vacatures
    folder: content/vacancies
    create: true
    fields:
      - {
          name: path,
          label: bestandnaam,
          hint: "enkel invullen bij maken nieuwe vacature of aanpassen bestandnaam bestaande vacature",
        }
      - { name: title, label: titel }
      - { name: date, label: datum, widget: datetime }
      - { name: body, label: omschrijving, widget: markdown }
      - label: afbeelding
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
  - name: promotions
    label: promoties
    folder: content/promotions
    create: true
    fields:
      - {
          name: path,
          label: bestandnaam,
          hint: "enkel invullen bij maken nieuwe vacature of aanpassen bestandnaam bestaande vacature",
        }
      - { name: title, label: titel }
      - { name: date, label: datum, widget: datetime }
      - label: afbeelding
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
  - name: "pages"
    label: "tekst voorpagina"
    files:
      - label: "voorpagina"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - { label: titel boven hoofd, name: titleOne, widget: string }
          - { label: titel twee, name: titleTwo, widget: string }
          - { label: titel drie, name: titleThree, widget: string }
          - { label: subtitel boven, name: subtitleOne, widget: text }
          - { label: subtitel twee, name: subtitleTwo, widget: text }
          - { label: subtitel drie, name: subtitleThree, widget: text }
          - { label: troef één, name: feature1, widget: string }
          - { label: troef twee, name: feature2, widget: string }
          - { label: troef drie, name: feature3, widget: string }
          - { label: troef vier, name: feature4, widget: string }
          - { label: troef één tekst, name: feature1Text, widget: text }
          - { label: troef twee tekst, name: feature2Text, widget: text }
          - { label: troef drie tekst, name: feature3Text, widget: text }
          - { label: troef vier tekst, name: feature4Text, widget: text }
          - { label: spotlight 1 tekst, name: titleOneSpot, widget: string }
          - { label: spotlight 2 tekst, name: titleTwoSpot, widget: string }
          - { label: spotlight 3 tekst, name: titleThreeSpot, widget: string }
